name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install Nix
      uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        
    - name: Setup Nix flakes
      run: |
        echo "experimental-features = nix-command flakes" | sudo tee -a /etc/nix/nix.conf
        
    - name: Cache Nix store
      uses: cachix/cachix-action@v14
      with:
        name: nix-community
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        
    - name: Build project
      run: |
        nix develop --command bash -c "
          mkdir -p build
          cd build
          cmake .. -G Ninja
          ninja
        "
        
    - name: Run tests
      run: |
        nix develop --command bash -c "
          cd build
          # Run threading examples to verify they work
          ./mutex_example
          ./condition_variable_example
          ./thread_pool_example
          ./threading_practice
        "

  build-macos:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install Nix
      uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        
    - name: Setup Nix flakes
      run: |
        echo "experimental-features = nix-command flakes" | sudo tee -a /etc/nix/nix.conf
        
    - name: Cache Nix store
      uses: cachix/cachix-action@v14
      with:
        name: nix-community
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        
    - name: Build project
      run: |
        nix develop --command bash -c "
          mkdir -p build
          cd build
          cmake .. -G Ninja
          ninja
        "
        
    - name: Run tests
      run: |
        nix develop --command bash -c "
          cd build
          # Run threading examples to verify they work
          ./mutex_example
          ./condition_variable_example
          ./thread_pool_example
          ./threading_practice
        "
